# Generated by Django 4.0 on 2023-03-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tempdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdata',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
