# Generated by Django 4.0 on 2023-03-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_picdata_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picdata',
            name='chip',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='picdata',
            name='chunk_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='picdata',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempdata',
            name='chunk_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
