# Generated by Django 4.0 on 2023-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_picdata_chip_alter_picdata_chunk_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicDataImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='pics/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='picdata',
            name='image',
        ),
        migrations.AddField(
            model_name='picdata',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='picdata',
            name='images',
            field=models.ManyToManyField(to='core.PicDataImage'),
        ),
    ]
