# Generated by Django 4.0 on 2023-04-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_picdataimage_remove_picdata_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picdata',
            name='images',
        ),
        migrations.AddField(
            model_name='picdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
        migrations.DeleteModel(
            name='PicDataImage',
        ),
    ]
