# Generated by Django 4.0 on 2023-04-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_chunk_id_picdata_pic_id_tempdata_pic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picdata',
            name='vision',
            field=models.TextField(default=''),
        ),
    ]
